//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_JorgeIsaacLópezV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleFacturas = new HashSet<DetalleFacturas>();
        }
    
        public int Id_Producto { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Id_Estado { get; set; }
        public int Id_TipoProducto { get; set; }
        public decimal Precio_Unitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual TiposProductos TiposProductos { get; set; }
    }
}
